#!/bin/bash

# Modify /etc/hosts to set the IP address for localhost to 127.0.0.2
sudo sed -i 's/^127\.0\.0\.1/127.0.0.2/g' /etc/hosts

# Add an entry to /etc/hosts to set the IP address for facebook.com to 8.8.8.8
sudo echo '8.8.8.8 facebook.com' >> /etc/hosts
